L58 support
BRACKETS-by-TRIAD/advanced-logger pull request #2
Opened 2019-03-23 20:21 UTC by palypster

2019-03-25 07:40 UTC, dejwCake approved these changes
Looks ok to me :)

2019-04-12 10:13 UTC, dejwCake requested changes
One minor bug.

2019-04-12 10:13 UTC, dejwCake commented on composer.json
> -            "dev-master": "1.0-dev"
This should be not changed.

2019-08-08 08:20 UTC, dejwCake approved these changes

2019-08-09 06:34 UTC, branikclimbs approved these changes

2019-08-12 07:52 UTC, strstensky approved these changes

2019-08-14 07:31 UTC, RichardDominik approved these changes

2019-08-27 12:47 UTC, merged